config/routes.rb
Rails.application.routes.draw do
  get 'pregnancy/top'
  get 'infertility/top'
  get 'abouts/top'
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}


root 'abouts#top'
get 'infertility/top' => 'infertility#top', as:"infer_top" 
get 'pregnancy/top' => 'pregnancy#top',as:"preg_top" 


resources :admins, only:[:show, :edit, :update] 

# 名前空間上のroute
namespace :admin do
  resources :users ,only: [:show, :index, :destroy]
  resources :hosps, only: [:index, :show, :destroy] 
  resources :hosp_reviews, only: [:index, :destroy]
  resources :searchs, only: [:index]
  get 'recommends/infertility' => 'recommends#index', as:"infer_index"
  get 'recommends/pregnancy' => 'recommends#list', as:"preg_list"
  get 'recommends/human' => 'recommends#summary', as:"human_summary"

  resources :recommends, only: [:show, :destroy] 
  resources :regrets, only: [:index, :create, :destroy]
end

namespace :user do
  resources :users,only: [:show, :edit, :update, :destroy]
  resources :hosps do
    resources :hosp_reviews, only: [:create, :edit, :update, :destroy]
    resource :hosp_likes, only: [:create, :destroy]
  end
  get 'recommends/infertility/new' => 'recommends#new', as:"infer_new" 
  post 'recommends/infertility' => 'recommends#create', as:"infer_create"
  get 'recommends/infertility' => 'recommends#index', as:"infer_index"

  get 'recommends/pregnancy/latest' => 'recommends#latest', as:"preg_latest"
  post 'recommends/pregnancy' => 'recommends#complet', as:"preg_comp"
  get 'recommends/pregnancy' => 'recommends#list', as:"preg_list"

    resources :recommends, only: [:show, :edit, :update, :destroy] do
      resource :recommend_likes, only: [:create, :destroy]
    end
  resources :recommend_likes, only:[:index]
  resources :regrets, only: [:index, :create, :destroy]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hosp.rb
class Hosp < ApplicationRecord
    belongs_to :user
    belongs_to :prefecture
    has_many :hosp_reviews, dependent: :destroy
    has_many :hosp_likes, dependent: :destroy
    
    def favorited_by?(user)
        hosp_likes.where(user_id: user.id).exists?
    end

    validates :name, presence: true
    validates :user_id, presence: true
    validates :prefecture_id, presence: true
    validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :hosps, dependent: :destroy
  has_many :hosp_reviews, dependent: :destroy
  has_many :hosp_likes, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommend_likes, dependent: :destroy
  has_many :regrets, dependent: :destroy

  validates :name, presence: true
  validates :nickname, presence: true
  validates :tel, presence: true

end

app/controllers/admin/hosps_controller.rb
class Admin::HospsController < ApplicationController
    before_action :authenticate_admin!
    def index
        @q= Hosp.includes(:prefecture).ransack(params[:q])
        @hosps = @q.result(distinct: true).reverse_order
    end
    def show
        @hosp = Hosp.find(params[:id])
    end

    def destroy
        @hosp = Hosp.find(params[:id])
        @hosp.destroy
        redirect_to admin_hosps_path
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
    def index
        @users = User.all
    end

    def show
      @user = User.find(params[:id])
      
    end

    def destroy
    end

    private
    def user_params
      params.require(:user).permit(:name, :tel, :email, :password, :nickname)
    end
end

app/controllers/user/hosp_likes_controller.rb
class User::HospLikesController < ApplicationController
    def create
        hosp = Hosp.find(params[:hosp_id])
        hosp_like = current_user.hosp_likes.new(hosp_id: hosp.id)
        hosp_like.save
        redirect_to user_hosp_path(hosp)
    end

    def destroy
        hosp = Hosp.find(params[:hosp_id])
        hosp_like = current_user.hosp_likes.find_by(hosp_id: hosp.id)
        hosp_like.destroy
        redirect_to user_hosp_path(hosp)
    end
end

app/controllers/user/hosp_reviews_controller.rb
class User::HospReviewsController < ApplicationController
	before_action :authenticate_user!
    def create
		hosp = Hosp.find(params[:hosp_id])
		hosp_review = current_user.hosp_reviews.new(hosp_review_params)
		hosp_review.hosp_id = hosp.id
		if hosp_review.save
		   flash[:success] = "コメントを投稿しました！"
           redirect_back(fallback_location: root_url)
        else
			flash[:success] = "コメントの投稿に失敗しました！"
			redirect_back(fallback_location: root_url)
        end
	end

	def destroy
		hosp_review = HospReview.find(params[:id])
	if  hosp_review.destroy
		flash[:success] = "コメントを削除しました！！！"
        redirect_back(fallback_location: root_url)
    else
        redirect_back(fallback_location: root_url)
    end
	end

	def edit
		@hosp_review = HospReview.find(params[:id])
		@hosp = Hosp.find(params[:hosp_id])
		if @hosp_review.user.id != current_user.id
			redirect_to user_hosp_path(@hosp)
		end
	end

	def update
		@hosp = Hosp.find(params[:hosp_id])    
		@hosp_review = HospReview.find(params[:id])
		if @hosp_review.update(hosp_review_params)
			flash[:success] = "レビューを編集しました！"
			redirect_to user_hosp_path(@hosp)
		 else
			@hosp = Hosp.find(params[:hosp_id])	
			render :edit
		 end
	end

    private
	def hosp_review_params
		params.require(:hosp_review).permit(:hosp_id, :user_id, :body )
	end
end

app/controllers/user/hosps_controller.rb
class User::HospsController < ApplicationController
    def new
        @hosp = Hosp.new
    end

    def index
        @q= Hosp.includes(:prefecture).ransack(params[:q])
        @hosps = @q.result(distinct: true).reverse_order
        # いいねされていないものが表示されなくなる。いいね数順番
        # @hosps = Hosp.find(HospLike.group(:hosp_id).order('count(hosp_id) desc').pluck(:hosp_id))
    end
    
    def show
        @hosp = Hosp.find(params[:id])
        @hosp_review = HospReview.new
        @hosp.hosp_reviews.reverse_order
    end

    def edit
        @hosp = Hosp.find(params[:id])
        if @hosp.user.id != current_user.id
           redirect_to user_hosp_path(@hosp.id)
        end
    end

    def create
        @hosp = Hosp.new(hosp_params)
        @hosp.user_id = current_user.id
        if  @hosp.save
            flash[:success] = " 投稿しました！"
            redirect_to user_hosps_path
        else
            render :new
        end
    end

    def update
        @hosp = Hosp.find(params[:id])
        if  @hosp.update(hosp_params)
            flash[:success] = " 投稿しました！"
            redirect_to user_hosp_path(@hosp.id)
        else
            render :edit
        end     
    end

    def destroy
        @hosp = Hosp.find(params[:id])
        @hosp.destroy
        redirect_to user_hosps_path
    end

    private
    def hosp_params
        params.require(:hosp).permit(:name, :user_id, :prefecture_id, :body)
    end  
end

app/controllers/user/recommend_likes_controller.rb
class User::RecommendLikesController < ApplicationController
    def index
        # @recommend_likes = Recommend.where(user_id: params[:id])
        if user_signed_in?
            @recommend_likes = current_user.recommend_likes
        end
    end


    def create
        recommend = Recommend.find(params[:recommend_id])
        recommend_like = current_user.recommend_likes.new(recommend_id: recommend.id)
        recommend_like.save
        redirect_to user_recommend_path(recommend)
    end

    def destroy
        recommend = Recommend.find(params[:recommend_id])
        recommend_like = current_user.recommend_likes.find_by(recommend_id: recommend.id)
        recommend_like.destroy
        redirect_to user_recommend_path(recommend)
    end
end

app/controllers/user/recommends_controller.rb
class User::RecommendsController < ApplicationController
    # 不妊側 infertility
    def new
        @recommend = Recommend.new
    end
    
    def create
        @recommend = Recommend.new(recommend_params)
        @recommend.user_id = current_user.id
        if  @recommend.save
            flash[:success] = " 投稿しました！"
            redirect_to user_infer_index_path
        else
            render :new
        end
    end

    def index 
        @recommends = Recommend.where(term: '不妊').reverse_order
    end

    # 妊娠側 pregnancy
    def latest
        @recommend = Recommend.new
    end

    def complet
        @recommend = Recommend.new(recommend_params)
        @recommend.user_id = current_user.id
        if  @recommend.save
            flash[:success] = " 投稿しました！"
            redirect_to user_preg_list_path
        else
            render :latest
        end
    end

    def list
        @recommends = Recommend.where(term: '妊娠').reverse_order
    end

    # 両方
    def show
        @recommend = Recommend.find(params[:id])
    end

    def edit
        @recommend = Recommend.find(params[:id])
        if @recommend.user.id != current_user.id
            redirect_to user_recommend_path(@recommend)
            end
    end

    def update
        @recommend = Recommend.find(params[:id])
        if  @recommend.update(recommend_params)
            flash[:success] = " 変更しました！"
            rredirect_to user_recommend_path(@recommend)
        else
            render :edit
        end
    end
    
    def destroy
        @recommend = Recommend.find(params[:id])
        @recommend.destroy
        if @recommend.term == 'infertility'
            redirect_to user_infer_index_path
        else
            redirect_to user_preg_list_path
        end
    end
    
    private
    def recommend_params
      params.require(:recommend).permit(:term, :user_id, :genre, :title, :body)
    end
  
end

# if @recommend.term == 'infertility'
#     redirect_to user_infer_index_path
# else 
#     redirect_to user_preg_list_path
# end

app/controllers/user/regrets_controller.rb
class User::RegretsController < ApplicationController
    def index
        @regret = Regret.new
        @regrets = Regret.all.reverse_order
    end
    
    def create
        @regret = Regret.new(regret_params)
        @regret.user_id = current_user.id
        if  @regret.save
            flash[:success] = " 投稿しました！"
            redirect_back(fallback_location: root_url)
        else
            @regrets = Regret.all
            @regret.user_id = current_user.id    
            render :index
        end
    end

    def destroy
        @regret = Regret.find(params[:id])
        if  @regret.destroy
            flash[:success] = "削除しました！！！"
            redirect_back(fallback_location: root_url)
        else
            redirect_back(fallback_location: root_url)
        end
    end

    private
    def regret_params
    params.require(:regret).permit(:user_id, :period_id, :body )
    end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def show
      @user = User.find(params[:id])
      if @user.id != current_user.id
        redirect_to user_user_path(current_user)
    end
  end

  def edit
      @user = User.find(params[:id])
      if @user.id != current_user.id
          redirect_to user_user_path(current_user)
      end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
          redirect_to user_user_path(@user.id)
      else render :edit
      end
  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to new_user_session_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :tel, :email, :nickname)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/hosps_helper.rb
module Admin::HospsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/hosp_likes_helper.rb
module User::HospLikesHelper
end

app/views/user/hosps/edit.html.erb
 <div class='body'>
    <div class="container">
        <section class="row row-eq-height">
        <h2 class="col-xs-7 col-xs-offset-5">病院編集</h2>

                <% if flash[:success] %>
                <p class="text-center"><%= flash[:success] %></p>
                <% end %>

                <% if @hosp.errors.any? %>
                <div id="error_explanation" class="alert alert-danger">
                <ul>
                <% @hosp.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
                <% end %>

            <div class="col-xs-2">
                <div class="sidebar"> 
                    <%= render 'layouts/infsidebar' %>
                </div>
            </div>
            
            <div class='col-xs-10'>
            <%= form_for @hosp, url: user_hosp_path(@hosp) do |hosp| %>
                <label class="control-label" for="inputname">病院名</label>
                <%= hosp.text_field :name, class:"form-control"%>

                <h4 class="col-xs-12">都道府県</h4>
                <%= hosp.collection_select :prefecture_id,  Prefecture.all, :id, :name, {}, placeholder: "選択してください", class: 'form-control h4' %> 

                <label class="control-label" for="inptbody">内容</label>
                <%= hosp.text_field :body, class:"form-control"%>

                <%= hosp.submit "変更する", class:"form-control btn btn-primary" %>
            <% end %>
            </div>
        </section>
    </div>
</div>

app/views/user/hosps/index.html.erb
<div class="body">
    <div class="container">
        <section class="row">
        <h2 class="col-xs-7 col-xs-offset-5">おすすめ病院一覧</h2>
        
            <% if flash[:success] %>
            <p><%= flash[:success] %></p>
            <% end %>

            <div class="col-xs-2">
                <div class="sidebar">
                    <%= render 'layouts/infsidebar' %>
                </div>
            </div>

            <div class="col-xs-10">
                      <!-- 検索窓をつける -->
                        <div class="kensaku clearfix">
                            <%= search_form_for @q, url: user_hosps_path do |f| %>

                            <div class="head-form">
                            <%= f.search_field :name_cont, placeholder: '病院名', class:"form-control" %>
                            </div>
                            <div class="head-form">
                            <%= f.search_field :prefecture_name_cont, placeholder: '都道府県', class:"form-control" %>                           
                            </div>
                            <div class="head-form">
                            <%= f.submit "検索", class:"btn btn-default" %>
                            </div>
                            <% end %>
                        </div>


                        <div class="hospmain">
                        
                            <p class="hosptext"><b>医院の名前</p><br>
                            <p class="hosptext"><b>都道府県はここだったよ</p><br>
                            <p class="hosptext"><b>こんなところ良かった！事が書いてあるよ！</p><br>
                            <p class="hosptext"><b>行ってみて良かったよボタン</p><br>
                        </div>

                        <% @hosps.each do |hosp| %>
                        <div class="hospall">
                            <p>医院の名前：<br><%= hosp.name %></p><br>
                            <p>都道府県：<br><%= hosp.prefecture.name %></p><br>
                            <p>内容：<br><%= hosp.body %></p><br>
                            <p><%= hosp.hosp_likes.count %> オススメ</p><br>
                            <p><%= link_to "詳細を見る", user_hosp_path(hosp.id), class:"btn btn-default form-control" %></p>
                        </div>
                        <% end %>
            </div>
        </section>
    </div>
</div>

app/views/user/hosps/new.html.erb
<div class='body'>
    <div class="container">
        <section class="row row-eq-height">
        <h2 class="col-xs-7 col-xs-offset-5">おすすめの病院登録</h2>
            <div class="text-center">
                <% if flash[:success] %>
                <p class="text-center"><%= flash[:success] %></p>
                <% end %>

                <% if @hosp.errors.any? %>
                <div id="error_explanation" class="alert alert-danger">
                <br>
                <% @hosp.errors.full_messages.each do |message| %>
                <p><%= message %></p>
                <% end %>
                <% end %>
            </div>

            <div class="col-xs-2">
                <div class="sidebar"> 
                  <%= render 'layouts/infsidebar' %>
                </div>
            </div>
            
            <div class='col-xs-10'>
            <% if user_signed_in? %>
            <div class="hospbox">
                <%= form_for @hosp, url: user_hosps_path do |hosp| %>
                    <h4 class="col-xs-12">病院名</h4>
                    <%= hosp.text_field :name  %>

                    <h4 class="col-xs-12">都道府県</h4>
                    <%= hosp.collection_select :prefecture_id,  Prefecture.all, :id, :name, {}, placeholder: "選択してください", class: 'form-control h4' %> 

                    <h4 class="col-xs-12">内容</h4>
                    <p class="">どんな風によかったか、書いてね！</p>
                    <%= hosp.text_area :body, class:"form-control" %>
                    <div class="hosplink">
                    <%= hosp.submit "登録する", class:"btn btn-default text-center" %>
                    </div>
                    </div>
                <% end %>
            </div>
            <% else %>
            <div class="unuser text-center">
                <h4 class="unlink"><b>会員登録すると、自分のオススメを登録できるよ！</h4></b>
                <b><%= link_to_unless_current "ログインする", new_user_session_path, class:"unlink text-center h5" %></b>
                <%= link_to_unless_current "会員登録する", new_user_registration_path, class:"unlink text-center h5" %>
            <% end %>
            </div>
            </div>
        </section>
    </div>
</div>

app/views/user/hosps/show.html.erb
<%# 病院の詳細だよ〜〜 %>
<div class='body'>
    <div class='container'>
        <div class='row row-eq-height'>
            <h2 class="col-xs-7 col-xs-offset-5">おすすめ病院 詳細</h2>
            <div class="col-xs-2">
                <div class="sidebar">   
                    <%= render 'layouts/infsidebar' %>
                </div>
            </div>

            <div class='col-xs-10'>

                    <% if flash[:success] %>
                    <p class="text-center"><%= flash[:success] %></p>
                    <% end %>

                    <% if @hosp_review.errors.any? %>
                    <div id="error_explanation" class="alert alert-danger">
                    <ul>
                    <% @hosp_review.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                    <% end %>

                <div class="hospmain clearfix">

                    <label class="hosptext"><b>医院の名前</label><br>
                    <label class="hospbodytext">
                    <h4 class="hosptext"><%= @hosp.name %></h4>
                    </label><br>

                    <label class="hosptext"><b>都道府県</label><br>
                    <label class="hospbodytext">
                    <h4 class="hosptext"><%= @hosp.prefecture.name%></h4>
                    </label><br>

                    <label class="hosptext"><b>内容</label><br>
                    <label class="hospbodytext">
                    <h4 class="hosptext"><%= @hosp.body %></h4>
                    </label><br>

                    <% if user_signed_in? %>
                    <%# いいね!ボタンの実装  %>
                        <div class="hosplike clearfix">
                                <p class="" style="color:#20B2AA"><b>良かった医院をオススメしよう！</p>

                            <% if @hosp.favorited_by?(current_user) %>
                                <%= link_to  user_hosp_hosp_likes_path(@hosp), method: :delete do %>
                                <span class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 60px; color: #C71585"></span>
                                <% end %>
                                <%= @hosp.hosp_likes.count %> オススメ

                            <% else %>
                                <%= link_to  user_hosp_hosp_likes_path(@hosp), method: :post do %>
                                <span class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 60px; color: #555555"></span>
                                <% end %>
                                <%= @hosp.hosp_likes.count %> オススメ

                            <% end %>
                        </div>
                            
                    <% else %>
                        <div class="text-center">
                            <h4 class="unlink"><b>会員登録して、良かった医院をオススメしよう！</h4>                
                        </div>
                    <% end %>

                    <div class="hospedit">
                    <% if user_signed_in? && current_user.id == @hosp.user.id  %>
                    <%= link_to "編集する",  edit_user_hosp_path , class:"btn btn-default form-control" %>                      
                    <%= link_to "削除する", user_hosp_path(@hosp.id), class:"btn btn-danger", method: :delete %>
                    <% end %>
                    </div>
                </div>
              

              <%# review %>
                <div class="">
                    <h3 class="text-center"><b>ユーザーレビュー</b></h3>
                    
                    <% @hosp.hosp_reviews.each do |review| %>
                        <div class="review">
                            <%# <p><%= review.user.nickname %>
                            <p><%= review.body %></p>

                            <% if user_signed_in? && current_user.id == review.user_id %>
                            <label class="reviewlink"><%= link_to "編集", edit_user_hosp_hosp_review_path(@hosp.id,review.id), class:"botan1" %></label>
                            <label class="reviewlink"><%= link_to "削除", user_hosp_hosp_review_path(@hosp.id,review.id), method: :delete %></label>
                            <% end %>
                        </div>
                    <% end %>
                </div>

                    <% if user_signed_in? %>
                        <%= form_for [@hosp, @hosp_review], url:user_hosp_hosp_reviews_path(@hosp)  do |f| %>
                        <%= f.text_area :body, class: "form-control",placeholder: "コメントをここに" %>
                        <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                        <% end %>
                    <% end %>
            </div>
        </div>
    </div>
</div>