config/routes.rb
Rails.application.routes.draw do
  get 'pregnancy/top'
  get 'infertility/top'
  get 'abouts/top'
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}


root 'abouts#top'
get 'infertility/top' => 'infertility#top', as:"infer_top" 
get 'pregnancy/top' => 'pregnancy#top',as:"preg_top" 


resources :admins, only:[:show, :edit, :update] 

# 名前空間上のroute
namespace :admin do
  resources :users ,only: [:show, :index, :destroy]
  resources :hosps, only: [:index, :show, :destroy] 
  resources :hosp_reviews, only: [:index, :destroy]
  resources :searchs, only: [:index]
  get 'recommends/infertility' => 'recommends#index', as:"infer_index"
  get 'recommends/pregnancy' => 'recommends#list', as:"preg_list"
  get 'recommends/human' => 'recommends#summary', as:"human_summary"

  resources :recommends, only: [:show, :destroy] 
  resources :regrets, only: [:index, :create, :destroy]
end

namespace :user do
  resources :users,only: [:show, :edit, :update, :destroy]
  resources :hosps do
    resources :hosp_reviews, only: [:create, :edit, :update, :destroy]
    resource :hosp_likes, only: [:create, :destroy]
  end
  get 'recommends/infertility/new' => 'recommends#new', as:"infer_new" 
  post 'recommends/infertility' => 'recommends#create', as:"infer_create"
  get 'recommends/infertility' => 'recommends#index', as:"infer_index"

  get 'recommends/pregnancy/latest' => 'recommends#latest', as:"preg_latest"
  post 'recommends/pregnancy' => 'recommends#complet', as:"preg_comp"
  get 'recommends/pregnancy' => 'recommends#list', as:"preg_list"

    resources :recommends, only: [:show, :edit, :update, :destroy] do
      resource :recommend_likes, only: [:create, :destroy]
    end
  resources :recommend_likes, only:[:index]
  resources :regrets, only: [:index, :create, :destroy]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recommend.rb
class Recommend < ApplicationRecord
    belongs_to :user
    has_many :recommend_likes, dependent: :destroy
    def favorited_by?(user)
        recommend_likes.where(user_id: user.id).exists?
    end

    enum term: {不妊: 0,妊娠: 1}
    #０妊活 １妊娠

    validates :user_id, presence: true
    validates :genre, presence: true
    validates :title, presence: true
    validates :body, presence: true
    validates :term, presence: true

end

app/controllers/admin/recommends_controller.rb
class Admin::RecommendsController < ApplicationController
    before_action :authenticate_admin!
    def index
        @recommends = Recommend.where(term: '不妊').reverse_order
    end

    def list
        @recommends = Recommend.where(term: '妊娠').reverse_order
    end

    def summary
        @recommends = Recommend.all.reverse_order
    end
    
    def show
        @recommend = Recommend.find(params[:id])
    end
        
    def destroy
        @recommend = Recommend.find(params[:id])
        @recommend.destroy
        redirect_to admin_human_summary_path
    end
end

app/controllers/user/recommends_controller.rb
class User::RecommendsController < ApplicationController
    # 不妊側 infertility
    def new
        @recommend = Recommend.new
    end
    
    def create
        @recommend = Recommend.new(recommend_params)
        @recommend.user_id = current_user.id
        if  @recommend.save
            flash[:success] = " 投稿しました！"
            redirect_to user_infer_index_path
        else
            render :new
        end
    end

    def index 
        @recommends = Recommend.where(term: '不妊').reverse_order
    end

    # 妊娠側 pregnancy
    def latest
        @recommend = Recommend.new
    end

    def complet
        @recommend = Recommend.new(recommend_params)
        @recommend.user_id = current_user.id
        if  @recommend.save
            flash[:success] = " 投稿しました！"
            redirect_to user_preg_list_path
        else
            render :latest
        end
    end

    def list
        @recommends = Recommend.where(term: '妊娠').reverse_order
    end

    # 両方
    def show
        @recommend = Recommend.find(params[:id])
    end

    def edit
        @recommend = Recommend.find(params[:id])
        if @recommend.user.id != current_user.id
            redirect_to user_recommend_path(@recommend)
            end
    end

    def update
        @recommend = Recommend.find(params[:id])
        if  @recommend.update(recommend_params)
            flash[:success] = " 変更しました！"
            rredirect_to user_recommend_path(@recommend)
        else
            render :edit
        end
    end
    
    def destroy
        @recommend = Recommend.find(params[:id])
        @recommend.destroy
        if @recommend.term == 'infertility'
            redirect_to user_infer_index_path
        else
            redirect_to user_preg_list_path
        end
    end
    
    private
    def recommend_params
      params.require(:recommend).permit(:term, :user_id, :genre, :title, :body)
    end
  
end

# if @recommend.term == 'infertility'
#     redirect_to user_infer_index_path
# else 
#     redirect_to user_preg_list_path
# end

app/helpers/admin/recommends_helper.rb
module Admin::RecommendsHelper
end

app/helpers/user/recommends_helper.rb
module User::RecommendsHelper
end

app/views/admin/recommends/index.html.erb
<div class='body'>
    <div class='container'>
        <section class="row">
            <h2 class="text-center">不妊側おすすめ一覧</h2>

            <div class='col-xs-12'>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>投稿者ID</th>
                            <th>ジャンル</th>
                            <th>タイトル</th>
                            <th>内容</th>   
                            <th></th>
                            </tr>
                    </thead>
                    <tbody>
                        <% @recommends.each do |recommend| %>
                        <tr>
                            <td>
                            <%= link_to admin_user_path(recommend.user_id) do %>
                            <%= recommend.user_id %>
                            <% end %></td>
                            <td><%= recommend.genre %></td>
                            <td><%= recommend.title %></td>
                            <td><%= recommend.body %></td>
                            <td><%= link_to "詳細を見る", admin_recommend_path(recommend.id), class:"btn btn-success" %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
 </div>

app/views/admin/recommends/list.html.erb
<div class='body'>
    <div class="container">

        <section class="row">
            <h1 class="col-xs-10 col-xs-offset-2">妊娠側おすすめ一覧</h1>
            <div class='col-xs-12'>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>投稿者ID</th>
                        <th>ジャンル</th>
                        <th>タイトル</th>
                        <th>内容</th>
                        <th></th>
                        </tr>
                </thead>
                <tbody>
                    <% @recommends.each do |recommend| %>
                    <tr>
                        <td>
                         <%= link_to admin_user_path(recommend.user_id) do %>
                        <%= recommend.user_id %>
                        <% end %></td>
                        <td><%= recommend.genre %></td>
                        <td><%= recommend.title %></td>
                        <td><%= recommend.body %></td>
                        <td><%= link_to "詳細を見る", admin_recommend_path(recommend.id), class:"btn btn-success" %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        </section>
    </div>
 </div>

app/views/admin/recommends/show.html.erb
<div class='body'>
    <div class="container">
        <section class="row">
            <h1 class="col-xs-11 col-xs-offset-1">おすすめ情報 詳細</h1>
                <div class='col-xs-12'>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>投稿者ID</th>
                                <th>ジャンル</th>
                                <th>タイトル</th>
                                <th>内容</th>   
                                <th>区分</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                <%= link_to admin_user_path(@recommend.user_id) do %>
                                <%= @recommend.user_id %>
                                <% end %></td>
                                <td><%= @recommend.genre %></td>
                                <td><%= @recommend.title %></td>
                                <td><%= @recommend.body %></td>
                                <td><%= @recommend.term %></td>
                            </tr>
                        </tbody>
                    </table>
                        <div class="form-group has-icon">
                            <%= link_to "削除する", admin_recommend_path(@recommend.id), class:"alert-link btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></div>
                        </div>
                </div>
        </section>
    </div>
</div>

app/views/admin/recommends/summary.html.erb
<div class='body'>
    <div class='container'>
        <section class="row">
            <h2 class="text-center">全てのおすすめ投稿一覧</h2>


            <%= link_to "不妊側おすすめ", admin_infer_index_path, class:"btn btn-success" %>
            <%= link_to "妊娠側おすすめ", admin_preg_list_path, class:"btn btn-success" %>


 
            <div class='col-xs-12'>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>投稿者ID</th>
                            <th>区分</th>
                            <%# <th>投稿者名</th> %>
                            <%# <th>ジャンル</th> %>
                            <th>タイトル</th>
                            <th>内容</th>   
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @recommends.each do |recommend| %>
                        <tr>
                            <td>
                             <%= link_to admin_user_path(recommend.user_id) do %>
                            <%= recommend.user_id %>
                            <% end %></td>
                            <%# <td><%= recommend.user.name %> 
                            <td><%= recommend.term %></td>
                            <%# <td><%= recommend.genre %></td>
                            <td><%= recommend.title %></td>
                            <td><%= recommend.body %></td>
                            <td><%= link_to "詳細", admin_recommend_path(recommend.id), class:"btn btn-success" %>
                            <td><%= link_to "削除", admin_recommend_path(recommend.id), class:"alert-link btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>

                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
 </div>